---
title: "FBref Data"
author: "Fahad Alkhaja"
date: "4/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(rstanarm)
library(gt)
library(tidybayes)
```

```{r load_EPL_fixtures_results_table}
EPL_Results_18_19 <- read_csv("FBRef_Data/EPL_Results_18:19.csv",
                              col_types = cols(
                                Wk = col_double(),
                                Day = col_character(),
                                Date = col_character(),
                                Time = col_character(),
                                Home = col_character(),
                                xGHome = col_double(),
                                `Home Goals Scored` = col_double(),
                                `Away Goals Scored` = col_double(),
                                xGAway = col_double(),
                                Away = col_character(),
                                Attendance = col_number(),
                                Venue = col_character(),
                                Referee = col_character(),
                                `Match Report` = col_character(),
                                Notes = col_logical() ))
```


```{r load_EPL_end_of_league_table}

EPL_LeagueTable_18_19 <- read_csv("FBRef_Data/EPL_LeagueTable_18:19.csv",
                                  col_types = cols(
                                    Rk = col_double(),
                                    Squad = col_character(),
                                    MP = col_double(),
                                    W = col_double(),
                                    D = col_double(),
                                    L = col_double(),
                                    GF = col_double(),
                                    GA = col_double(),
                                    GD = col_double(),
                                    Pts = col_double(),
                                    xG = col_double(),
                                    xGA = col_double(),
                                    xGD = col_double(),
                                    `xGD/90` = col_double(),
                                    Attendance = col_number(),
                                    `Top Team Scorer` = col_character(),
                                    Goalkeeper = col_character(),
                                    Notes = col_character() ))

```

```{r results_sorting}

epl_results <- EPL_Results_18_19 %>%
  select(Home:Away) %>%
  drop_na()

# Here an xPts model based on the xG difference of a game was computed, if xG of
# a team is greater than the other they get an xPts of 3 and the other team an
# xPts of 0, if they are the same, the xPts received is 1 for both teams.

HA_epl_results <- epl_results %>%
  mutate(PtsHome = if_else(`Home Goals Scored` - `Away Goals Scored` > 0,
                           3,
                           if_else(`Away Goals Scored` - `Home Goals Scored` > 0,
                                   0, 1))) %>%
  mutate(PtsAway = if_else(PtsHome == 3, 0, if_else(PtsHome == 1, 1, 3))) %>%
  mutate(xPtsHome = if_else(xGHome - xGAway > 0,
                            3,
                            if_else(xGAway - xGHome > 0, 0, 1))) %>%
  mutate(xPtsAway = if_else(xPtsHome == 3, 0, if_else(xPtsHome == 1, 1, 3)))

epl_results_proper_form <- HA_epl_results %>% 
  pivot_longer(cols = c("Home", "Away"),
               names_to = "Home/Away",
               values_to = "Team") %>%
  mutate(xG = if_else(`Home/Away` == "Home", xGHome, xGAway),
         xG_Against = if_else(`Home/Away` == "Home", xGAway, xGHome),
         Goals_Scored = if_else(`Home/Away` == "Home",
                                `Home Goals Scored`, `Away Goals Scored`),
         Goals_Conceded = if_else(`Home/Away` == "Home",
                                  `Away Goals Scored`, `Home Goals Scored`),
         Pts = if_else(`Home/Away` == "Home", PtsHome, PtsAway),
         xPts = if_else(`Home/Away` == "Home", xPtsHome, xPtsAway)) %>% 
  select(`Home/Away`:xPts) %>%
  group_by(Team)
  
# As the table had shown values for each of 38 games per team, to get the total
# means summing up all the columns while gruoping by team.

arranged_stuff_all <- epl_results_proper_form %>%
  summarize(results_xG = sum(xG),
            results_xG_Against = sum(xG_Against),
            results_Goals_Scored = sum(Goals_Scored),
            results_Goals_Conceded = sum(Goals_Conceded),
            results_Pts = sum(Pts),
            results_xPts = sum(xPts),
            .groups = "drop") %>%
  mutate(results_GD = results_Goals_Scored - results_Goals_Conceded) %>% 
  mutate(results_xGD = results_xG - results_xG_Against) %>% 
  mutate(results_xPts_Pts_Difference = results_Pts - results_xPts) %>% 
  
  # In order to account for teams that have the same number of points, a
  # tiebreaker is used. In this specific competition, the tiebreaker is Goal
  # Difference (GD). The Team with the Higher Goal Difference is awarded the
  # higher place. If GD is the same then a H2H or Head to Head record between
  # the teams has to be examined. This case is not looked at because there are
  # no cases of GD and Pts being the same for any team.
  
  arrange(-results_Pts, -results_GD)

arranged_stuff_specific <- arranged_stuff_all  %>%
  select(Team, results_Pts, results_xPts, results_GD, results_xGD) %>%
  
  # The following is a way to generate two columns of team names to be 
  mutate(Team_Pts = Team,
         Team_xPts = Team) %>%
  select(Team_xPts,Team_Pts, results_Pts, results_xPts, results_GD, results_xGD)

# arranged_xPts <- arranged_Pts %>%
#   arrange(desc(results_xPts))

arranged_Pts <- arranged_stuff_specific %>%
  arrange(-results_Pts, -results_GD) %>%
  select(Team_Pts, results_Pts)


arranged_xPts <- arranged_stuff_specific %>%
  
  # Since the tiebreaker is GD for Pts, it is only fair to use xGD as the
  # tiebreaker for xPts table.
  
  arrange(-results_xPts, -results_xGD) %>%
  select(Team_xPts, results_xPts)

```

```{r organizing_for_fit}

newfit_epl_results <- epl_results %>%
  mutate(Goal_Difference = `Home Goals Scored` - `Away Goals Scored`) %>%
  mutate(PtsHome = if_else(`Home Goals Scored` - `Away Goals Scored` > 0,
                           3,
                           if_else(`Away Goals Scored` - `Home Goals Scored` > 0,
                                   0, 1))) %>%
  mutate(PtsAway = if_else(PtsHome == 3, 0, if_else(PtsHome == 1, 1, 3))) %>%
  mutate(xPtsHome = if_else(xGHome - xGAway > 0,
                            3,
                            if_else(xGAway - xGHome > 0, 0, 1))) %>%
  mutate(xPtsAway = if_else(xPtsHome == 3, 0, if_else(xPtsHome == 1, 1, 3)))

# Here GD and xGD terms were added that can be used if a more complicated model
# is needed,

newfit_epl_results_pivoted <- newfit_epl_results %>% 
  pivot_longer(cols = c("Home", "Away"),
               names_to = "Home/Away",
               values_to = "Team") %>%
  mutate(xG = if_else(`Home/Away` == "Home", xGHome, xGAway),
         Goals_Scored = if_else(`Home/Away` == "Home",
                                `Home Goals Scored`, `Away Goals Scored`),
         Pts = if_else(`Home/Away` == "Home", PtsHome, PtsAway),
         xPts = if_else(`Home/Away` == "Home", xPtsHome, xPtsAway),
         GD = if_else(`Home/Away` == "Home", Goal_Difference, -Goal_Difference),
         xGD = if_else(`Home/Away` == "Home", xGHome-xGAway, xGAway-xGHome),
         `GD-xGD` = round(GD - xGD, 2)) %>%
  select(`Home/Away`:`GD-xGD`) %>%
  group_by(Team, `Home/Away`)
  
newfit_epl_results_pivoted_summary <- newfit_epl_results_pivoted %>%
  summarize(xG = round(mean(xG), 3),
            Pts =round(mean(Pts), 3),
            xPts = round(mean(xPts), 3),
            GD = round(mean(GD), 3),
            xGD = round(mean(xGD), 3),
            `GD-xGD` = round(mean(`GD-xGD`), 3),
            .groups = "drop")
```


```{r new_fit}
fit_1_PL <- stan_glm(data = newfit_epl_results_pivoted,
                 formula = Pts ~  Team + `Home/Away` + xGD + `GD-xGD` + xPts + Team*`Home/Away`,
                 family = gaussian,
                 seed = 25,
                 refresh = 0)

 
 fit1_gt <- tbl_regression(fit_1_PL, 
               intercept = TRUE, 
               estimate_fun = function(x) style_sigfig(x, digits = 3)) %>%
  as_gt() %>% 
  tab_header(title = md("**Number of Points to be Obtained per Game**"),
             subtitle = "How Team, Location, GD and xGD affect Points") %>%
  tab_source_note(md("Source: FBRef via StatsBomb")) %>% 
  cols_label(estimate = md("**Parameter**"))
 

 
 fit_2_PL <- stan_glm(data = newfit_epl_results_pivoted,
                 formula = Pts ~  Team + `Home/Away`+ xPts,
                 family = gaussian,
                 seed = 25,
                 refresh = 0)

  
  fit_model_PLtable <- tbl_regression(fit_2_PL, 
               intercept = TRUE, 
               estimate_fun = function(x) style_sigfig(x, digits = 3)) %>%
  
  
  as_gt() %>% 
  tab_header(title = md("**Number of Points to be Obtained per Game**"),
             subtitle = "How Team, Home/Away, and xPts affect Points") %>%
  tab_source_note(md("Source: FBRef via StatsBomb")) %>% 
  cols_label(estimate = md("**Parameter**"))
  
  # saveRDS(fit_model_PLtable, "soccer_model/fit_model_PLtable.RDS")

  # Here I had to manually look at the fit outputs,he alternative was computing
  # several mutates and pivoting which was too painstaking
  
  team_effect <- tibble(Team = unique(newfit_epl_results_pivoted_summary$Team),
                        Effect = c(0, -0.284, -0.388, -0.231,-0.023, -0.042,
                                   -0.167,-0.238, 0.030, 0.841, 0.288, 0.039,
                                   0.034, -0.727, 0.019, -0.283, 0.127,
                                   -0.442, -0.297, -0.126))
  
  
  final_model_table <- newfit_epl_results_pivoted_summary %>%
    select(Team, `Home/Away`, xPts) %>%
    right_join(team_effect, by = "Team") %>% 
    mutate(`Home/Away` = if_else(`Home/Away` == "Home", 1, 0)) %>%
    mutate(model_Pts_Location = 0.813 + xPts*0.360 + `Home/Away`*0.263 + Effect) %>%
    select(Team, `Home/Away`, model_Pts_Location) %>%
    pivot_wider(values_from = model_Pts_Location,
                names_from = `Home/Away`) %>%
    rename(Away_model_PPG = `0`,Home_model_PPG = `1`) %>%
    mutate(Model_PPG = round((Away_model_PPG + Home_model_PPG)/2 , 3),
           Model_Pts = round(Model_PPG * 38, 3)) %>%
    select(Team, Model_PPG, Model_Pts) %>%
    arrange(desc(Model_Pts))
  
  

```

```{r}

# Here I join my model compared to the xPts model to the actual league table
joined_xPts_Pts_modelxPts <- tibble(
  Position = 1:20,
  `Pts Table` = arranged_Pts$Team_Pts,
  Pts = arranged_Pts$results_Pts,
  PPG = round(Pts/38, 3),
  `xPts Table` = arranged_xPts$Team_xPts,
  xPts = arranged_xPts$results_xPts,
  xPPG = round(xPts/38, 3),
  `Model Table` = final_model_table$Team,
  `Model Pts` = final_model_table$Model_Pts,
  `Model PPG` = final_model_table$Model_PPG)

# Now I make this table look nice as a gt, and save it as an RDS filee

final_gt_model_table <- joined_xPts_Pts_modelxPts %>%
  gt() %>%
  tab_source_note(md("Source: FBRef via StatsBomb")) %>%
  tab_header(title = md("**English Premier League 2019/20 League Table**"),
             subtitle = "Comparing Pts vs xPts vs Model-xPts")

# saveRDS(final_gt_model_table, "soccer_model/final_gt_model_table.RDS")
```



